apiVersion: apps/v1
kind: Deployment
metadata: # metadata do deployment
  name: backend-dp
  labels:
    app: backend-app
    type: backend
spec:
  template:
    metadata: # metadata do container
      name: backend-pod
      labels:
        app: backend-app
        type: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      type: backend
  replicas: 3
